Show help text if pictool is called without args
This fixes:
(py39) tom@thymian:~/devel/pictool$ pictool
Traceback (most recent call last):
  File "/home/tom/devel/pictool/.tox/py39/bin/pictool", line 10, in <module>
    sys.exit(main())
  File "/home/tom/devel/pictool/pictool/__init__.py", line 469, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'